### ISSUE TITLE
Getting Connection Exceptions with the SDK

### ISSUE THREAD

**Issue by jagan120** [googlemaps/google-maps-services-java#267] opened 2017-05-19 01:02 UTC
We have been using the SDK since a long time but, have observed that it started erroring recently. The Stack trace I see is this :

```
java.net.ConnectException: Failed to connect to maps.googleapis.com/2607:f8b0:4000:803:0:0:0:200a:443
	at com.squareup.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:143) ~[okhttp-2.7.5.jar:?]
	at com.squareup.okhttp.internal.io.RealConnection.connect(RealConnection.java:112) ~[okhttp-2.7.5.jar:?]
	at com.squareup.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184) ~[okhttp-2.7.5.jar:?]
	at com.squareup.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126) ~[okhttp-2.7.5.jar:?]
	at com.squareup.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95) ~[okhttp-2.7.5.jar:?]
	at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281) ~[okhttp-2.7.5.jar:?]
	at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224) ~[okhttp-2.7.5.jar:?]
	at com.squareup.okhttp.Call.getResponse(Call.java:286) ~[okhttp-2.7.5.jar:?]
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243) ~[okhttp-2.7.5.jar:?]
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205) ~[okhttp-2.7.5.jar:?]
	at com.squareup.okhttp.Call.access$100(Call.java:35) ~[okhttp-2.7.5.jar:?]
	at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:171) ~[okhttp-2.7.5.jar:?]
	at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33) ~[okhttp-2.7.5.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1153) [?:1.8.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:1.8.0]
	at java.lang.Thread.run(Thread.java:785) [?:?]
```

**Comment by mwithake** [comment] 2017-05-29 08:16
We have the same problem. Do you use IBM i?

**Comment by domesticmouse** [comment] 2017-05-29 08:54
I'm confused as to how that "address" is getting generated. Is it some form of IPv6 embedding?

**Comment by mwithake** [comment] 2017-05-29 09:39
Sorry, I don't know how the address is generated.

We are using IBM i (AS400). With the help of IBM, we found the problem. 
In jre/lib/java.security IBM has changed jdk.tls.disabledAlgorithms:
jdk.tls.disabledAlgorithms=SSLv3, RC4, MD5withRSA, DH keySize < 768, 3DES_EDE_CBC, DESede

After removing DESede, it works. IBM declares DESede as unsafe. Is the API using DESede?

**Comment by jagan120** [comment] 2017-05-30 19:22
We use IBM Liberty, which has IBM Java. So the main problem is with that. If this SDK wants to be compatible with IBM Java which removed support for the 3DES as pointed [here](https://github.com/square/okhttp/issues/3173), the okhttp dependency needs to be upgraded to 3.7+. I started working on it after a separate [issue](https://github.com/googlemaps/google-maps-services-java/issues/148#issuecomment-297169027), but did not get the time to finish it yet.

**Comment by domesticmouse** [comment] 2017-06-19 06:31
I'm going to close this out as a dupe of #148. Thanks!

**Closed by domesticmouse** 2017-06-19 06:31 UTC
