### ISSUE TITLE
Register an InstanceCreator with Gson

### ISSUE THREAD

**Issue by clembou590** [googlemaps/google-maps-services-java#170] opened 2016-08-23 00:01 UTC
the issue seems to be linked to this one:
https://github.com/googlemaps/google-maps-services-java/issues/54

I am trying to use this library on GAE. (in version 0.1.15)

I get this error:

> java.lang.RuntimeException: Unable to invoke no-args constructor for class com.google.maps.model.EncodedPolyline. Register an InstanceCreator with Gson for this type may fix this problem.

my question is this:
why in the class: OkHttpPendingResult

you do all this:
Gson gson = new GsonBuilder()
        .registerTypeAdapter(DateTime.class, new DateTimeAdapter())
        .registerTypeAdapter(Distance.class, new DistanceAdapter())
        .registerTypeAdapter(Duration.class, new DurationAdapter())
        .registerTypeAdapter(Fare.class, new FareAdapter())
        .registerTypeAdapter(LatLng.class, new LatLngAdapter())
.....

but you do not register the EncodedPolyline with an adapter?

or you could tell me how to do to get rid of this error (ON GOOGLE APP ENGINE...) without adding it (but I do see why not add it...)

thanks

**Comment by domesticmouse** [comment] 2016-10-04 03:15
Hmm, I'm confused as to why the above is causing an issue. Can you please construct a minimal test case app that demonstrates this issue, and put it up on GitHub so I can reproduce the problem? This helps enormously with confirming the fix works as intended, along with guiding additional unit tests to prevent future regressions. Thanks!

**Comment by gnyekhelyi** [comment] 2016-10-07 11:10
I have the same issue on GOOGLE APP ENGINE.

See paulbakker's comment on issue #54.

> It turns out the issue was caused by my environment. GSON has a feature (that I didn't know about) to create instances without a no-arg constructor using the sun.misc.Unsafe class. Because I'm running in an OSGi container this class is not available by default, and GSON was swallowing the exception. 

So it might be the issue here too sun.misc.Unsafe is not available on GAE.

**Comment by BhalchandraSW** [comment] 2017-03-11 12:10
I am facing the same issue running the app from Android Studio 2.3 and v0.1.17. My issue is with `NearbySearchRequest$Response`
_Unable to invoke no-args constructor for class com.google.maps.NearbySearchRequest$Response. Register an InstanceCreator with Gson for this type may fix this problem._

I am able to invoke `PlacesApi.placeDetails(sContext, placeId).await();` successfully, but not `PlacesApi.nearbySearchQuery(sContext, new LatLng(location.getLat(), location.getLng()));`

**Comment by domesticmouse** [comment] 2017-06-19 07:46
I believe this issue was fixed in https://github.com/googlemaps/google-maps-services-java/pull/260

**Closed by domesticmouse** 2017-06-19 07:46 UTC
