### ISSUE TITLE
Lib not fully supported on GAE?

### ISSUE THREAD

**Issue by littletower** [googlemaps/google-maps-services-java#145] opened 2016-03-30 13:48 UTC
Hi!

So I'm running the following code  on my GAE app:
```
GeoApiContext context = new GeoApiContext().setApiKey(GOOGLE_API_KEY);
DistanceMatrix d = DistanceMatrixApi.newRequest(context)
        .origins(orgLatLng)
        .destinations(destLatLng)
        .awaitIgnoreError();
```

But that gives me the following exception:
```
Caused by: java.lang.NoClassDefFoundError: java.net.ProxySelector is a restricted class. Please see the Google  App Engine developer's guide for more details.
	at com.google.appengine.tools.development.agent.runtime.Runtime.reject(Runtime.java:52)
	at com.squareup.okhttp.OkHttpClient.copyWithDefaults(OkHttpClient.java:459)
	at com.squareup.okhttp.OkHttpClient.newCall(OkHttpClient.java:439)
	at com.google.maps.internal.OkHttpPendingResult.<init>(OkHttpPendingResult.java:96)
	at com.google.maps.GeoApiContext.getWithPath(GeoApiContext.java:152)
	at com.google.maps.GeoApiContext.get(GeoApiContext.java:79)
	at com.google.maps.PendingResultBase.makeRequest(PendingResultBase.java:78)
	at com.google.maps.PendingResultBase.awaitIgnoreError(PendingResultBase.java:61)
```

Am I doing something wrong here? Or did Google let me down on this one? ;)

thanks

**Comment by domesticmouse** [comment] 2016-03-31 00:49
This is a duplicate of #47 

Supporting GAE isn't a direct goal of the project, but we will happily take PR that implement the functionality without breaking other deployment scenarios. Thanks!

**Closed by domesticmouse** 2016-03-31 00:49 UTC
