### ISSUE TITLE
Version 0.15.1 of google-maps-services is not available in maven central repo

### ISSUE THREAD

**Issue by per-ostgard-wcar** [googlemaps/google-maps-services-java#703] opened 2020-12-18 08:19 UTC
I specify my dependency on google-maps-services like so
`
<dependency>
<groupId>com.google.maps</groupId>
<artifactId>google-maps-services</artifactId>
<version>0.15.1</version>
</dependency>`

But I get an error "Could not find artifact com.google.maps:google-maps-services:pom:0.15.1"

A manual search at search.maven.org gives not hits on 0.15.1 either

Could you please add the 0.15.1 version to the maven central repo?

**Comment by hisener** [comment] 2021-01-20 06:00
Not exactly what you are looking for but v0.15.4 is on Maven Central. 🎉

**Comment by jpoehnelt** [comment] 2021-01-28 15:10
duplicate of #695

**Comment by jpoehnelt** [comment] 2021-01-28 15:11
Investigating, @arriolac has been manually publishing.

**Closed by jpoehnelt** 2021-01-28 15:10 UTC
Labels: triage me, type: bug
