### ISSUE TITLE
Java 8 problem

### ISSUE THREAD

**Issue by powder366** [googlemaps/google-maps-services-java#306] opened 2017-08-03 10:20 UTC
After 0.1.20 you compile with Java 8, does not work with Android app.
I added 

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_7
        targetCompatibility JavaVersion.VERSION_1_7
    }

but still does not work for me. Reverted to version 0.1.20
Please advice.

**Comment by gabrielsalmeida** [comment] 2017-08-03 14:47
In my project this was caused by guava 22.0 dependency inside build.gradle of google-maps-services-java. I corrected it locally and submitted a pull request to change guava version. Hope it helps you.

**Comment by domesticmouse** [comment] 2017-08-11 04:48
@gabrielsalmeida's fix (https://github.com/googlemaps/google-maps-services-java/pull/308) will be in the next release, but please do not use this library in Android. Please see [Making the most of the Google Maps Web Service APIs](https://maps-apis.googleblog.com/2016/09/making-most-of-google-maps-web-service.html) for my explanation as to why this is a bad idea. Thanks!

**Closed by domesticmouse** 2017-08-11 04:48 UTC
