### ISSUE TITLE
Cannot use the library from AppEngine 

### ISSUE THREAD

**Issue by kaskaderc** [googlemaps/google-maps-services-java#62] opened 2015-01-30 09:58 UTC
Java in GAE is a "sandboxed" version and the sandbox does not allow creating new threads:
https://cloud.google.com/appengine/docs/java/?csw=1#Java_The_sandbox

https://github.com/googlemaps/google-maps-services-java/blob/master/src/main/java/com/google/maps/internal/RateLimitExecutorService.java#L58 causes   access denied ("java.lang.RuntimePermission" "modifyThreadGroup")
(full stack trace below)

To fix this we should follow the instructions from: https://cloud.google.com/appengine/docs/java/?csw=1#Java_The_sandbox

Should we maybe  work around this so that the lib works on appengine?
At least can we add a custom error message suggestion this might be the root cause?

    access denied ("java.lang.RuntimePermission" "modifyThreadGroup")
Caused by:

java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "modifyThreadGroup")
        at java.security.AccessControlContext.checkPermission(AccessControlContext.java:457)
        at java.security.AccessController.checkPermission(AccessController.java:884)
        at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
        at com.google.appengine.tools.development.DevAppServerFactory$CustomSecurityManager.checkPermission(DevAppServerFactory.java:429)
        at com.google.appengine.tools.development.DevAppServerFactory$CustomSecurityManager.checkAccess(DevAppServerFactory.java:454)
        at java.lang.ThreadGroup.checkAccess(ThreadGroup.java:315)
        at java.lang.Thread.init(Thread.java:391)
        at java.lang.Thread.init(Thread.java:349)
        at java.lang.Thread.<init>(Thread.java:461)
        at com.google.maps.internal.RateLimitExecutorService.<init>(RateLimitExecutorService.java:55)
        at com.google.maps.GeoApiContext.setQueryRateLimit(GeoApiContext.java:224)
        at com.google.maps.GeoApiContext.setQueryRateLimit(GeoApiContext.java:210)
        at com.google.maps.GeoApiContext.<init>(GeoApiContext.java:56)
        at com.sellbytel.geo.WebServicesJavaClientLib.GeoWsSamples.testGeocodeSimple(GeoWsSamples.java:213)
        at org.apache.jsp.geocodesimple_jsp._jspService(geocodesimple_jsp.java:70)

**Comment by vinz486** [comment] 2015-06-17 16:03
I have same issue.

Maybe the solution could be don't use threads at all.

:-(

**Comment by gilberto-torrezan** [comment] 2016-02-01 20:52
On AppEngine I can control the rate of the execution by using [push queues](https://cloud.google.com/appengine/docs/java/taskqueue/overview-push). And I can automatically retry tasks when those return an error too. So all the stuff that needs threads on the library can be done outside the library on AppEngine with little-to-no effort.

The library should provide a class to access the web services directly, without all the threading related stuff.

**Comment by domesticmouse** [comment] 2016-02-02 03:32
I think this report is a duplicate of https://github.com/googlemaps/google-maps-services-java/issues/47

Kasia, we accept pull requests =)

**Closed by domesticmouse** 2016-02-02 03:32 UTC
