### ISSUE TITLE
0.1.21 Thread problem still here.

### ISSUE THREAD

**Issue by magicmarkus99** [googlemaps/google-maps-services-java#287] opened 2017-07-05 13:52 UTC
The thread RateLimitExecutorDelayThread is still here.
And for each request i can found a RateLimitExecutorDelayThread in WAITING state.

**Comment by domesticmouse** [comment] 2017-07-10 06:55
Ugh.

Can you put together a simple repro case that I can use for debugging and verification of the fix?

**Comment by magicmarkus99** [comment] 2017-07-12 10:04
Yes.
I use tomcat  java 1.8.0_121 tomcat Tomcat 8.0.43.
In attachment you can find my psi-probe thread screenshot.

![threadproblem](https://user-images.githubusercontent.com/26464942/28112661-2ff13500-66fa-11e7-8d6d-320704008e24.png)

**Comment by magicmarkus99** [comment] 2017-07-12 10:08
I use this code:

		GeoApiContext context = new GeoApiContext();
		context = context.setApiKey(MyGOOGLEKEY).setQueryRateLimit(3).setConnectTimeout(1, TimeUnit.SECONDS)
				.setReadTimeout(1, TimeUnit.SECONDS).setWriteTimeout(1, TimeUnit.SECONDS);

		try {
			GeocodingResult[] results = GeocodingApi.newRequest(context).address(address1)
					.components(ComponentFilter.locality(address2), ComponentFilter.administrativeArea(address3), ComponentFilter.country(address4))
					.await();

			if (results.length == 1) {
				bg.setLat(String.valueOf(results[0].geometry.location.lat));
				bg.setLon(String.valueOf(results[0].geometry.location.lng));
			}

		} catch (Exception e) {}

**Comment by magicmarkus99** [comment] 2017-07-12 10:13
is it ok recreate the GeoApiContext each time or is better to use a Singleton?
thanks

**Comment by domesticmouse** [comment] 2017-07-12 14:45
The library is designed for the `GeoApiContext` to be a singleton in your application, that way things like rate limiting will work as intended. That should eliminate most of the issues you are currently seeing.

**Comment by jjcampac** [comment] 2017-07-28 17:47
Hi. 
I've just started to use **google-maps-services-java**. At first, it looks pretty easy to use, but I'm getting same problems reported.
First, the testing environment:
```
Java jdk1.8.0_71
Server Glassfish 4
```
For getting the GeoApiContext, I'm using the Singleton pattern:
```
   private static GeoApiContext geoContext;  
   
   private  GeoApiContext getGeoContext() {
        if(geoContext == null) {
             geoContext = new GeoApiContext.Builder()
                     .apiKey(Constants.API_KEY)
                     .readTimeout(10000, TimeUnit.SECONDS)
                     .queryRateLimit(5)
                     .connectTimeout(1, TimeUnit.SECONDS)
                     .build();
        }
        return geoContext;
    }
```
So far so good. I'm able to get the context.  However, every time I try to search for some address...
```
        GeocodingApiRequest request = GeocodingApi.newRequest(getGeoContext())
                .address("some address")
                .region("ES")
                .resultType(AddressType.ROUTE);
```
...the application gets freeze and I get the error:
```
Grave:   Exception in thread "RateLimitExecutorDelayThread"
Grave:   java.lang.NoSuchMethodError: com.google.common.util.concurrent.RateLimiter.acquire()D
	at com.google.maps.internal.RateLimitExecutorService.run(RateLimitExecutorService.java:75)
	at java.lang.Thread.run(Thread.java:745)
```
I tried removing the **.apiKey(Constants.API_KEY)** method from the GeoApiContext and then I got a response from the server indicating I need an API Key, that is to say that I can reach the server.
Any idea?

**Comment by jjcampac** [comment] 2017-07-31 12:56
A few things to add to my last post.
I created a new clean project to test **google-maps-services-java**  and everything worked as it was supposed  to (well, I changed a bit the declaration of the request variable, but nothing important to this issue). That the whole thing worked means that the problem is in my original project, which is a REST webservice including very different libraries (hibernate, jersye, jackson, gson, httpclient....) Among them, I found one named **jersey-guava**, which is included by **jersey-media-multipart**. I guessed that this was causing the problem, so I added an exclusion to my pom file.
```
<dependency>
    <groupId>org.glassfish.jersey.media</groupId>
    <artifactId>jersey-media-multipart</artifactId>
    <version>2.9</version>
    <scope>provided</scope>
    <exclusions>
        <exclusion>
            <groupId>org.glassfish.jersey.bundles.repackaged</groupId>
            <artifactId>jersey-guava</artifactId>
        </exclusion>
    </exclusions>
</dependency>
```
I stopped the server, rebuilt the project and... exactly the same exception.
One step further, I even excluded the **guava** dependency in **google-maps-services**:
```
<dependency>
    <groupId>com.google.maps</groupId>
    <artifactId>google-maps-services</artifactId>
    <version>0.2.0</version>
    <exclusions>
        <exclusion>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
        </exclusion>
    </exclusions>
</dependency>
```
I'm still getting the exception, but in runtime, no in compilation time, which is strange because it's supposed there isn't any **guava** library in the project. Obviously, there must be another library injecting guava, but I can't find out wich one.

**Comment by qualebs** [comment] 2017-08-11 10:54
Hi everyone hope I'm not late to the party. Experiencing the same issue here. I am trying to do a `placeDetails` request so that I can get latitude and longitude from the response. But my WebApp freezes. I don't know what I am doing wrong. please help.
`
    public void createApartment(Map<String, String[]> parameters, User user) {
        try {
            GeoApiContext context = new GeoApiContext.Builder().apiKey("MY_API_KEY").build();
            PlaceDetails placeDetails = PlacesApi.placeDetails(context, "Nairobi").await();
            double lat = placeDetails.geometry.location.lat;
            double lng = placeDetails.geometry.location.lng;
//                add location to the apartment
            try (Session session = DRIVER.session()) {
                session.writeTransaction(new TransactionWork<Integer>() {
                    @Override
                    public Integer execute(Transaction t) {
//                    creates an apartment with a location, adds the apartment to apartment layer adds an outward relationship from user to apartment
                        StatementResult result = t.run("CREATE(a:Apartment{type: $type, rent: $rent, "
                                + "longitude: $longitude, latitude: $latitude, dateCreated: $dateCreated, uid: $uid}) "
                                + "WITH a CALL spatial.addNode('apartments', a) "
                                + "YIELD node MATCH(u:User) WHERE u.uid = $uid CREATE(u) -[:MOVING_OUT]-> (node)",
                                parameters(
                                        "type", parameters.get("type")[0],
                                        "rent", Integer.parseInt(parameters.get("rent")[0]),
                                        "longitude", Double.parseDouble(RandomStringUtils.randomNumeric(2)),
                                        "latitude", Double.parseDouble(RandomStringUtils.randomNumeric(2)),
                                        "dateCreated", System.currentTimeMillis(),
                                        "uid", RandomStringUtils.randomAlphanumeric(10),
                                        "uid", user.getUid()
                                ));

                        return 1;
                    }

                });
            }
        } catch (ApiException | InterruptedException | IOException apiException) {
            apiException.printStackTrace(System.out);
        }
    }
`

**Comment by domesticmouse** [comment] 2017-08-11 23:11
@qualebs and @jjcampac - are you on AppEngine perchance?

**Comment by qualebs** [comment] 2017-08-12 07:06
@domesticmouse No, not on GAE, but I was finally successful in making a request using google-maps-services-0.1.20 and the following dependencies.

    public static Coordinate getCoordinate(String locality) {
        Coordinate coordinate = null;
        try {
            GeocodingResult[] geocodingResults = GeocodingApi.geocode(context, "Kenya, " + locality).await();
            // if place is not found return use the default coordinates for kenya
            double lat = 0.0236;
            double lng = 37.9062;
            if (geocodingResults.length > 0) {
                GeocodingResult result = geocodingResults[0];
                coordinate = new Coordinate(result.geometry.location.lat, result.geometry.location.lng);
            }
        } catch (ApiException | InterruptedException | IOException ex) {
            Logger.getLogger(GeoCoder.class.getName()).log(Level.SEVERE, null, ex);
        }
        return coordinate;
    }

- slf4j-api-1.7.25.jar
- okhttp-2.7.5.jar
- joda-time-2.9.9.jar
- guava-23.0.jar
- okio-1.6.0.jar


I will keep trying future releases as they come until I get a newer version that works. But meanwhile the above butters my toast and I can work with that.

**Comment by domesticmouse** [comment] 2017-08-12 11:11
@qualebs looking at https://github.com/googlemaps/google-maps-services-java/blob/master/build.gradle#L50 I think you are missing the gson dependency. At a guess, your environment already supplies that somehow?

**Comment by domesticmouse** [comment] 2017-08-14 03:32
I can't see a singular issue that needs to be fixed in this bug, more a collection of questions that may be better handled on StackOverflow or the like? 

Please feel free to re-open new issues with descriptions of the bugs at hand and I'll look into fixing them. Thanks!

**Closed by domesticmouse** 2017-08-14 03:32 UTC
